// Code generated by errors-const v{{.version}} tool DO NOT EDIT.

package ably

// ably error codes
const(
	{{- range .codes}}
	Err{{key .|normalize|split " "|map "id" "ID"|map "clientId" "clientID"|map "tls" "TLS"|title|join ""}} = {{.}}
	{{- end}}
)