on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Using git grep to fail the build if any tab characters are found in source files (except Go files) - we use spaces for whitespace.
      # Using prettier to ensure JSON files have consistent formatting.
      - run: |
          ! git --no-pager grep $'\t' -- './*' ':!./go' || { echo 'ERROR: Lint failed! Source files must use spaces for whitespace.'; false; }
          npm ci
          npx prettier --check "**/*.json"
          npm test

  check-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Build for Go users
        run: |
          scripts/build-go.sh
