on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use the jq tool (included in GitHub runner environments) to simplistically validate JSON files.
      - run: |
        cd protocol
        cat protocol/errors.json | jq empty
        cat protocol/errorsHelp.json | jq empty
