# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

on: workflow_dispatch

jobs:
  publish-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ABLY_COMMON_GO_SSH_KEY }}

      - name: Build and then Publish to Downstream Repository for Go users
        run: |
          git config --global user.name "ably-common-publish-workflow"
          git config --global user.email "ably-common-publish-workflow@ably.com"
          scripts/publish-go.sh
