name: Sync Data to S3

on:
  push:
    branches:
      - main
    paths:
      - 'data/**/*.csv'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
  S3_PREFIX: ${{ secrets.S3_PREFIX }}

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-ably-common
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync CSV files to S3
        run: |
          echo "🔄 Syncing CSV files to S3..."
          echo "   Bucket: $S3_BUCKET"
          echo "   Path: $S3_PREFIX"
          
          # Upload with public-read ACL if the bucket serves public files
          # Remove --acl public-read if files should be private
          aws s3 sync data/ s3://${S3_BUCKET}/${S3_PREFIX}/ \
            --exclude "*" \
            --include "*.csv" \
            --delete
          
          echo "✅ Sync complete!"
          
          # List uploaded files
          echo ""
          echo "📋 Uploaded files:"
          aws s3 ls s3://${S3_BUCKET}/${S3_PREFIX}/ --recursive

  generate-and-sync:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate agent CSV
        run: npm run export:agents

      - name: Generate release data
        run: |
          # Only run if we have the required tokens
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ] && [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Generating release data..."
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            npm run fetch:agent-releases
          else
            echo "⚠️  Skipping release data generation (missing tokens)"
          fi

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-ably-common
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload generated files to S3
        run: |
          echo "📤 Uploading generated files to S3..."
          
          # Sync all CSV files maintaining folder structure
          aws s3 sync data/ s3://${S3_BUCKET}/${S3_PREFIX}/ \
            --exclude "*" \
            --include "*.csv" \
            --delete
          
          echo "✅ Upload complete!"
