name: Sync Data to S3

on:
  push:
    branches:
      - main
    paths:
      - 'data/**/*.csv'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
  S3_PREFIX: ${{ secrets.S3_PREFIX }}

jobs:
  generate-and-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate agent CSV
        run: npm run export:agents

      - name: Generate release data
        run: |
          # Ensure we have the required tokens
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ] || [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ Error: Missing required tokens (GITHUB_TOKEN or OPENAI_API_KEY)"
            exit 1
          fi

          echo "Generating release data..."
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          npm run fetch:agent-releases

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-ably-common
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload generated files to S3
        run: |
          echo "📤 Uploading generated files to S3..."
          
          # Sync all CSV files maintaining folder structure
          aws s3 sync data/ s3://${S3_BUCKET}/${S3_PREFIX}/ \
            --exclude "*" \
            --include "*.csv" \
            --delete
          
          echo "✅ Upload complete!"
